version: '3'

tasks:
  default:
    cmds:
      - task: test-all
      - task: build-all

  build-all:
    deps: [build-who, get-global-data, build-google-forecast]

  build-who:
    desc: Build chart from WHO COVID-19 global data.
    cmds:
      - go run .

  get-global-data:
    desc: Get CSV files; WHO COVID-19 global data and Tokyo patients data.
    dir: report/
    cmds:
      - curl -L -sS "https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients.csv" | gnkf nl -n lf -o ./tokyo/130001_tokyo_covid19_patients.csv
      - curl -L -sS "https://covid19.who.int/WHO-COVID-19-global-data.csv" -o WHO-COVID-19-global-data.csv
      - cat WHO-COVID-19-global-data.csv | jvgrep Japan > WHO-COVID-19-japan-data.csv || exit 0

  build-google-forecast:
    desc: Build chart from Google forecast data.
    dir: report/
    cmds:
      - go run report.go

  build-matsue:
    desc: Build infections map in Matsue.
    dir: report/matsue/
    cmds:
      - go run infections.go ./matsue-infections.xlsx > infections.dot
      - dot -Tpng -o ./infections.png infections.dot

  test-all:
    cmds:
      - task: clean
      - task: test
      - task: graph

  test:
    desc: Update modules, check vulns, test, and lint.
    cmds:
      - go mod verify
      - depm list -j | nancy sleuth -n
      - go test -shuffle on ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.45.0 golangci-lint run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  clean:
    desc: Clean module and build cache, and remove go.sum file.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache
      - go mod verify
      - go mod tidy -v -go=1.18

  graph:
    desc: Make grapth of dependency modules.
    cmds:
      - depm m --dot --dot-config dot-config.toml | dot -Tpng -o ./dependency.png
    sources:
      - ./go.mod
      - '**/*.go'
    generates:
      - ./dependency.png
